#!/usr/bin/with-contenv bash

## load /etc/environment vars first:
for line in $( cat /etc/environment ) ; do export $line > /dev/null; done

cd /home/rstudio
exec /terminal/ttyd -u 1000 -g 1000 sudo -u rstudio -H bash


